-- ==============================================================================
-- SQL Скрипт инициализации таблиц для калькулятора ремонта квартир (Supabase)
-- ==============================================================================

-- 1. Таблица компаний (Мультитенантность + Подключение Telegram ботов)
CREATE TABLE IF NOT EXISTS public.companies (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    subtitle TEXT DEFAULT 'Калькулятор ремонта квартир',
    city TEXT NOT NULL DEFAULT 'Москва и МО',
    phone TEXT NOT NULL DEFAULT '+7 (800) 555-35-35',
    status_text TEXT NOT NULL DEFAULT 'Работаем без предоплаты',
    secondary_coeff NUMERIC(4, 2) NOT NULL DEFAULT 1.15,
    logo_letter TEXT NOT NULL DEFAULT 'Р',
    badge_text TEXT DEFAULT 'PRO',
    admin_chat_id BIGINT,
    bot_token TEXT,
    bot_username TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Добавляем столбцы, если таблица уже существовала
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS admin_chat_id BIGINT;
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS bot_token TEXT;
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS bot_username TEXT;

-- 2. Таблица тарифов и расценок ремонта для каждой компании
CREATE TABLE IF NOT EXISTS public.pricing_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id TEXT REFERENCES public.companies(id) ON DELETE CASCADE UNIQUE NOT NULL,
    cosmetic_price NUMERIC(10, 2) NOT NULL DEFAULT 4500,
    capital_price NUMERIC(10, 2) NOT NULL DEFAULT 8500,
    designer_price NUMERIC(10, 2) NOT NULL DEFAULT 15000,
    design_project_price NUMERIC(10, 2) NOT NULL DEFAULT 2000,
    demolition_price NUMERIC(10, 2) NOT NULL DEFAULT 1200,
    materials_price NUMERIC(10, 2) NOT NULL DEFAULT 3500,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Таблица лидов и заявок на замер
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id TEXT REFERENCES public.companies(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    city TEXT NOT NULL,
    area NUMERIC(6, 2) NOT NULL,
    property_type TEXT NOT NULL,
    renovation_class TEXT NOT NULL,
    price_min NUMERIC(12, 2) NOT NULL,
    price_max NUMERIC(12, 2) NOT NULL,
    total_base_cost NUMERIC(12, 2) NOT NULL,
    active_options JSONB DEFAULT '[]'::jsonb,
    preferred_date TEXT,
    communication TEXT,
    comment TEXT,
    agreement_152fz BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Включение Row Level Security (RLS)
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- Политики доступа для анонимных пользователей (Telegram Mini App)
DROP POLICY IF EXISTS "Public companies are viewable by everyone" ON public.companies;
CREATE POLICY "Public companies are viewable by everyone" 
ON public.companies FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public pricing rules are viewable by everyone" ON public.pricing_rules;
CREATE POLICY "Public pricing rules are viewable by everyone" 
ON public.pricing_rules FOR SELECT USING (true);

DROP POLICY IF EXISTS "Anyone can create leads" ON public.leads;
CREATE POLICY "Anyone can create leads" 
ON public.leads FOR INSERT WITH CHECK (true);

-- ==============================================================================
-- Стартовые данные для 3-х компаний (демонстрация мультитенантности)
-- ==============================================================================

INSERT INTO public.companies (id, name, subtitle, city, phone, status_text, secondary_coeff, logo_letter, badge_text)
VALUES
    ('remont-pro', 'РемонтПро', 'Калькулятор ремонта квартир', 'Москва и МО', '+7 (800) 555-35-35', 'Работаем без предоплаты', 1.15, 'Р', 'PRO'),
    ('elite-stroi', 'ЭлитСтрой Премиум', 'Дизайнерский ремонт и отделка', 'Санкт-Петербург', '+7 (812) 345-67-89', 'Гарантия 5 лет по ГОСТ', 1.20, 'Э', 'ELITE'),
    ('master-remonta', 'МастерРемонт', 'Надежный ремонт под ключ', 'Казань', '+7 (843) 210-99-88', 'Без скрытых доплат', 1.10, 'М', 'МАСТЕР')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.pricing_rules (company_id, cosmetic_price, capital_price, designer_price, design_project_price, demolition_price, materials_price)
VALUES
    ('remont-pro', 4500, 8500, 15000, 2000, 1200, 3500),
    ('elite-stroi', 5200, 9800, 18000, 2500, 1500, 4200),
    ('master-remonta', 3900, 7400, 13500, 1700, 1000, 3100)
ON CONFLICT (company_id) DO NOTHING;
