-- ==============================================================================
-- SQL Скрипт инициализации таблиц для калькулятора ремонта квартир (Supabase)
-- ==============================================================================

-- 1. Таблица компаний (Мультитенантность + Подключение Telegram ботов)
CREATE TABLE IF NOT EXISTS public.companies (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    subtitle TEXT DEFAULT 'Калькулятор ремонта квартир',
    city TEXT NOT NULL DEFAULT 'Москва и МО',
    phone TEXT NOT NULL DEFAULT '+7 (800) 555-35-35',
    status_text TEXT NOT NULL DEFAULT 'Работаем без предоплаты',
    secondary_coeff NUMERIC(4, 2) NOT NULL DEFAULT 1.15,
    logo_letter TEXT NOT NULL DEFAULT 'Р',
    badge_text TEXT DEFAULT 'PRO',
    admin_chat_id BIGINT,
    bot_token TEXT,
    bot_username TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Добавляем столбцы, если таблица уже существовала
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS admin_chat_id BIGINT;
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS bot_token TEXT;
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS bot_username TEXT;
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS subscription_status TEXT DEFAULT 'expired';
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS subscription_until TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS plan_id TEXT DEFAULT '1m';
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS trial_leads_used INT DEFAULT 0;

-- 2. Таблица тарифов и расценок ремонта для каждой компании
CREATE TABLE IF NOT EXISTS public.pricing_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id TEXT REFERENCES public.companies(id) ON DELETE CASCADE UNIQUE NOT NULL,
    cosmetic_price NUMERIC(10, 2) NOT NULL DEFAULT 4500,
    capital_price NUMERIC(10, 2) NOT NULL DEFAULT 8500,
    designer_price NUMERIC(10, 2) NOT NULL DEFAULT 15000,
    design_project_price NUMERIC(10, 2) NOT NULL DEFAULT 2000,
    demolition_price NUMERIC(10, 2) NOT NULL DEFAULT 1200,
    materials_price NUMERIC(10, 2) NOT NULL DEFAULT 3500,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Таблица лидов и заявок на замер
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id TEXT REFERENCES public.companies(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    city TEXT NOT NULL,
    area NUMERIC(6, 2) NOT NULL,
    property_type TEXT NOT NULL,
    renovation_class TEXT NOT NULL,
    price_min NUMERIC(12, 2) NOT NULL,
    price_max NUMERIC(12, 2) NOT NULL,
    total_base_cost NUMERIC(12, 2) NOT NULL,
    active_options JSONB DEFAULT '[]'::jsonb,
    preferred_date TEXT,
    communication TEXT,
    address TEXT,
    comment TEXT,
    status TEXT DEFAULT 'new',
    agreement_152fz BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Таблица построчных расценок и смет строительных компаний (ГОСТ / СНиП)
CREATE TABLE IF NOT EXISTS public.company_estimate_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id TEXT REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
    category TEXT NOT NULL, -- 'demolition' | 'rough' | 'engineering' | 'finishing' | 'materials'
    item_code TEXT NOT NULL,
    title TEXT NOT NULL,
    unit TEXT NOT NULL DEFAULT 'м²',
    quantity_ratio NUMERIC(6, 3) NOT NULL DEFAULT 1.0,
    unit_price NUMERIC(10, 2) NOT NULL,
    tariff_applicability TEXT[] DEFAULT ARRAY['cosmetic', 'capital', 'designer'],
    description TEXT,
    order_index INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Включение Row Level Security (RLS)
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_estimate_items ENABLE ROW LEVEL SECURITY;

-- Политики доступа для анонимных пользователей (Telegram Mini App)
DROP POLICY IF EXISTS "Public companies are viewable by everyone" ON public.companies;
CREATE POLICY "Public companies are viewable by everyone" 
ON public.companies FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public pricing rules are viewable by everyone" ON public.pricing_rules;
CREATE POLICY "Public pricing rules are viewable by everyone" 
ON public.pricing_rules FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public company estimate items are viewable by everyone" ON public.company_estimate_items;
CREATE POLICY "Public company estimate items are viewable by everyone" 
ON public.company_estimate_items FOR SELECT USING (true);

DROP POLICY IF EXISTS "Anyone can create leads" ON public.leads;
CREATE POLICY "Anyone can create leads" 
ON public.leads FOR INSERT WITH CHECK (true);

-- ==============================================================================
-- Стартовые данные для 3-х компаний (демонстрация мультитенантности)
-- ==============================================================================

INSERT INTO public.companies (id, name, subtitle, city, phone, status_text, secondary_coeff, logo_letter, badge_text)
VALUES
    ('remont-pro', 'РемонтПро', 'Калькулятор ремонта квартир', 'Москва и МО', '+7 (800) 555-35-35', 'Работаем без предоплаты', 1.15, 'Р', 'PRO'),
    ('elite-stroi', 'ЭлитСтрой Премиум', 'Дизайнерский ремонт и отделка', 'Санкт-Петербург', '+7 (812) 345-67-89', 'Гарантия 5 лет по ГОСТ', 1.20, 'Э', 'ELITE'),
    ('master-remonta', 'МастерРемонт', 'Надежный ремонт под ключ', 'Казань', '+7 (843) 210-99-88', 'Без скрытых доплат', 1.10, 'М', 'МАСТЕР')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.pricing_rules (company_id, cosmetic_price, capital_price, designer_price, design_project_price, demolition_price, materials_price)
VALUES
    ('remont-pro', 4500, 8500, 15000, 2000, 1200, 3500),
    ('elite-stroi', 5200, 9800, 18000, 2500, 1500, 4200),
    ('master-remonta', 3900, 7400, 13500, 1700, 1000, 3100)
ON CONFLICT (company_id) DO NOTHING;

-- Базовые построчные расценки сметы для РемонтПро
INSERT INTO public.company_estimate_items (company_id, category, item_code, title, unit, quantity_ratio, unit_price, description, order_index)
VALUES
    ('remont-pro', 'demolition', 'demo-wallpaper', 'Демонтаж старых обоев, краски и шпаклевки', 'м²', 2.6, 140, 'Очистка оснований до штукатурного слоя', 1),
    ('remont-pro', 'demolition', 'demo-floors', 'Демонтаж старого линолеума / ламината и плинтусов', 'м²', 1.0, 180, 'Снятие финишного покрытия и подложки', 2),
    ('remont-pro', 'demolition', 'demo-screed', 'Демонтаж старой цементной стяжки до плиты', 'м²', 0.8, 550, 'Ударный демонтаж с сохранением перекрытия', 3),
    ('remont-pro', 'rough', 'rough-primer', 'Обеспыливание и грунтовка глубокого проникновения (2 слоя)', 'м²', 2.6, 85, 'Knauf Тифенгрунд', 4),
    ('remont-pro', 'rough', 'rough-plaster', 'Штукатурка стен по маякам с выведением углов 90°', 'м²', 2.6, 680, 'Лазерный контроль вертикалей', 5),
    ('remont-pro', 'rough', 'rough-screed', 'Устройство стяжки пола по маякам с фиброй', 'м²', 1.0, 580, 'Лазерный горизонт с перепадом до 2 мм', 6),
    ('remont-pro', 'rough', 'rough-waterproofing', 'Обмазочная гидроизоляция санузла с лентой', 'м²', 0.35, 480, 'Заход на стены 20 см', 7),
    ('remont-pro', 'engineering', 'eng-cables', 'Штробление и прокладка ГОСТ-кабеля ВВГнг-LS в гофре', 'пог. м', 1.8, 210, 'Без скруток, сварка гильзами', 8),
    ('remont-pro', 'engineering', 'eng-sockets', 'Высверливание подрозетников и монтаж стаканов (точки)', 'точек', 0.85, 490, 'Алмазное безударное коронкование', 9),
    ('remont-pro', 'engineering', 'eng-panel', 'Сборка силового электрощита с УЗО и реле напряжения', 'щит', 0.02, 9500, 'Автоматика ABB/Schneider/DEKraft', 10),
    ('remont-pro', 'engineering', 'eng-plumbing-pipes', 'Разводка труб водоснабжения Rehau из сшитого полиэтилена', 'точек', 0.16, 2400, 'Опрессовка давлением 10 атм', 11),
    ('remont-pro', 'engineering', 'eng-collector', 'Монтаж коллекторного узла с манометрами и фильтрами', 'узел', 0.02, 11500, 'Защита от гидроударов', 12),
    ('remont-pro', 'finishing', 'finish-putty', 'Шпаклевание стен финишной полимерной смесью (2 слоя)', 'м²', 2.6, 420, 'Под лампу Lossew', 13),
    ('remont-pro', 'finishing', 'finish-wallpaper', 'Оклейка стен бесшовными флизелиновыми обоями / покраска', 'м²', 2.3, 380, 'Невидимый стык', 14),
    ('remont-pro', 'finishing', 'finish-tiles', 'Укладка керамогранита с запилом углов под 45°', 'м²', 0.45, 1650, 'Система SVP, эпоксидная затирка', 15),
    ('remont-pro', 'finishing', 'finish-laminate', 'Настил ламината 33 класса / кварцвинила с подложкой', 'м²', 0.75, 460, 'Без порогов', 16),
    ('remont-pro', 'finishing', 'finish-doors', 'Установка межкомнатных дверей с доборами и фурнитурой', 'комплект', 0.065, 4200, 'Магнитные замки', 17),
    ('remont-pro', 'finishing', 'finish-ceiling', 'Монтаж натяжного потолка MSD Premium со светильниками', 'м²', 1.0, 780, 'Теневой профиль', 18)
ON CONFLICT DO NOTHING;
